name: Update Metrics on Push

on:
  push:
    branches:
      - main  # You can specify the branch where changes should trigger the workflow, e.g., 'main'

jobs:
  update-metrics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Git
      run: sudo apt-get install git

    - name: Run Python script
      run: python update_metrics.py

    - name: Commit and Push Changes
      run: |
        git config --local user.email "saikumaresh007@gmail.com"
        git config --local user.name "Sai Kumaresh"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Updated metrics in README.md"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
