name: Update Metrics on Push

on: [push]

jobs:
  update-metrics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Run Update Script
      run: python update_metrics.py

    - name: Commit Changes
      run: |
        git config --local user.email "saikumaresh007@gmail.com"
        git config --local user.name "Sai Kumaresh"
        git add README.md
        git commit -m "Updated metrics in README.md"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      continue-on-error: true  # In case there are no changes to commit

    - name: Push Changes
      run: |
        git push "https://${{ secrets.GH_TOKEN }}@github.com/saikumaresh/CodeFiles.git" HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
