name: Update Metrics on Push

on: [push]

jobs:
  update-metrics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Run Update Script
      run: python update_metrics.py

    - name: Commit Changes
      run: |
        git config --local user.email "saikumaresh007@gmail.com"
        git config --local user.name "Sai Kumaresh"
        git add README.md
        git commit -m "Updated metrics in README.md" || echo "No changes to commit"

    - name: Push Changes
      run: git push origin HEAD:main